# 验证MLP计算结果

In [1]:
import numpy as np

# 网络定义: input --> fc1 --> sigmod --> output

$$
\begin{bmatrix}
y_1 \\
y_2
\end{bmatrix}
=
sigmoid 
\left(
\begin{bmatrix}
w_{11} & w_{12} & w_{13} \\
w_{21} & w_{22} & w_{23}
\end{bmatrix}
*
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
+ 
\begin{bmatrix}
b_1 \\
b_2
\end{bmatrix}

\right)
$$

In [4]:
# 输入
input = [2, 4, 8]

# 权重, 生成6个小数, 转换成2行3列的矩阵
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6]).reshape(2, 3)

# bias
bias = [0.1, 0.5]


In [5]:
output = np.dot(weights, input) + bias

In [6]:
output

array([3.5, 8.1])

In [7]:
1 / (1 + np.exp(-output))

array([0.97068777, 0.99969655])

In [8]:
np.round(1 / (1 + np.exp(-output)), 6)

array([0.970688, 0.999697])